### ISSUE TITLE
Make app name more important than window title

### ISSUE THREAD

**Issue by Sobak** [Wox-launcher/Wox.Plugin.Switcheroo#9]
Hello,

Switcheroo plugin is great - that's almosts exactly what I was mainly looking for when trying different launchers. Following is of course just a proposal and I'm aware that it might not be the most popular usecase or user's excectation ...though, I think it is and that's why I'd like to discuss it.

In my opinion in case of switching opened windows, user is mainly intereset in application name and not title of the window. For example, when trying to switch to the browser, this plugin focuses on the window title mostly - being title of currently focused tab. In my case, I don't exactly remember what page I was browsing and I just want to switch to the browser quickly.

There are, of course, opposite situations - e.g. when you have ten different windows of Windows Explorer opened and you want to switch to specific folder. I think, thought, that it still would be possible taking my suggestion into account - application name would be just more prefered.

I would also like to sugggest filping app name with  windows title visually - to be consistent with that way of thinking.

One more time, this is just a humble idea - I would love to hear your thoughts, though.

**Comment by lances101** [comment]
hey there, @Sobak 
I like your idea. I think this could be added as a option that can be toggled in the Settings tab. That way the user adapts it to his own needs.

**Comment by Sobak** [comment]
That would be absolutely great

**Comment by Sobak** [comment]
I found another issue with a current behavior. My scenario: I had Opera Browser opened and wanted to "teach" Wox to prefer switching to its window over opening new (actually, a new tab, but it's irrelevant). I typed "opera", "oper", "op", selected Opera result from Switcheroo and repeated until its weight was inreased enough. It worked, great.

But here comes the problem: I had Facebook tab opened so for Wox, the title was "Facebook - Opera". Then I switched current tab to something else, let it be "Foobar - Opera" and it has default weight again. I fully understand it - "Facebook - Opera" is different result than "Foobar - Opera", but maybe flipping title with description, as I suggested, would solve this issue as well?

**Comment by lances101** [comment]
This plugin does not weight the results, they are weighted by Wox. And as far as I'm aware (this should be checked though), Wox weights it based on the score of the Fuzzy Matcher + how often a specific result is chosen. I could force a recalculation of the score to match how the results arrive from Switcheroo itself. 

_**Totally offtopic**_
I have considered ditching Switcheroo ([the core functionality](https://github.com/kvakulo/Switcheroo)) for half a year now. At this point it has not been updated for a year. I was planning to remake the plugin to target [GoToWindow](https://github.com/christianrondeau/GoToWindow) which has tab support for applications via plugins, but it has been also silent for 7 months now ☹️  Seems like launchers and the like are not that popular on Windows or something, idk. If you know of a similar project I would take a look into taking their core functionality and developing a plugin for Wox with that.

**Comment by Sobak** [comment]
Sure, I know that  the core is responsible for weighting. I suppose, however, that each result is identified by the title, not the description. If I'm right, then "Facebook - Opera" and "Foobar - Opera" would have the same title of "opera" (application name) and their respective descriptions. Then they would be considered same result and weighting should work as expected.

I might be wrong, though, so I'll try to Read The F... Source and come up with more useful thoughts.

PS: I would also suppose launchers to be more popular on Windows - I might be biased but for me it's not "geek-only" kind of workflow. It's just convenient and has big potential.

**Comment by lances101** [comment]
Sorry I cannot be more helpful right now. I will have more time to look into it during the weekend.

**Comment by lances101** [comment]
Just updated Switcheroo to `1.0.8`. Added two new options:
- an option to display applications first and the rest of the title last. Instead of "Github.com - Google Chrome" you will get "Google Chrome - Github.com"
- an option to swap the title and subtitle places

@Sobak please report back once you have updated the Switcheroo plugin. You can do so by typing `wpm install Switcheroo` into Wox

**Comment by lances101** [comment]
@Sobak regarding your comment about the weighting system... For each page it will be different. I believe Wox stores the weight for **_specific_** results. Again, this can be changed by some extra weighting. 

**Edit:**About that "extra" weighting... I think I could just nuke it completely and make all of them return the same score for it. I will now test what Switcheroo actually returns. 

**Edit 2:** right now its is not possible to pass unweighted results to Wox. Whatever I do, the `MainViewModel` will always add the frequency score. This can be seen here: [Wox\ViewModel\MainViewModel.cs, Lines 614-624](https://github.com/Wox-launcher/Wox/blob/master/Wox/ViewModel/MainViewModel.cs#L614-L624)

This requires a change to Wox's `Plugin` class, which is the most untouchable thing we have due to it being used to by plugin developers. It would require some discussion and considerations, which is even more complicated at this point because @happlebao has been missing/busy for quite some time now.

**Comment by lances101** [comment]
App name swap is already implemented. Closing this up. As for the weighting, if it's still relevant for the current version of Wox, please create a new issue.
